Repository SysBioChalmers/RAVEN, pull requests merged in 2018-10, with the labels that each got.

#166 fix: find toolbox version
  io/exportForGit.m
Labels: bug

#167 feat: generateNewIds function, addRxns has allowNewGenes flags and uses default bounds
  core/addGenesRaven.m
  core/addMets.m
  core/addRxns.m
  core/addRxnsGenesMets.m
  core/changeRxns.m
  core/checkModelStruct.m
  core/generateNewIds.m
  core/standardizeGrRules.m
  readme/RAVEN_structure_fields.csv
  readme/RAVEN_structure_fields.xlsx
Labels: bug, feature

#176 Feat/readTags
  io/exportForGit.m
  io/getVersion.m
Labels: feature

#178 fix: update rxnGeneMat when new genes added
  core/addGenesRaven.m
  core/addRxns.m
  core/addRxnsGenesMets.m
Labels: bug
