Repository SysBioChalmers/RAVEN, pull requests merged in 2020-06, with the labels that each got.

#295 fix: rule conversion in raven-cobra wrapper
  struct_conversion/ravenCobraWrapper.m
Labels: COBRA, bug

#299 fix: correct capitalization metBiGGID
  struct_conversion/COBRA_structure_fields.csv
  struct_conversion/ravenCobraWrapper.m
  struct_conversion/standardizeModelFieldOrder.m
Labels: bug

#302 Fix/met id conversion wrapper
  struct_conversion/ravenCobraWrapper.m
Labels: COBRA, bug

#301 feat: collect old and new genes
  core/getModelFromHomology.m
Labels: feature

#303 feat: exportForGit folder behaviour & import COBRA modelID
  io/exportForGit.m
  io/importModel.m
Labels: COBRA, bug, feature
